import { HeroClassId, EquipmentType } from './constants';

export interface ExerciseTemplate {
  id: string;
  name: string;
  sets: number;
  reps: string;
  notes?: string;
  videoQuery: string;
  equipment: EquipmentType[];
  heroClasses: HeroClassId[];
  difficultyLevel: 1 | 2 | 3; // 1=beginner, 2=intermediate, 3=advanced
  category: 'strength' | 'hiit' | 'mobility' | 'cardio';
}

export interface WorkoutTemplate {
  name: string;
  type: string;
  exerciseIds: string[];
  duration: number;
}

export const EXERCISE_LIBRARY: ExerciseTemplate[] = [
  // ─── WARRIOR: Bodyweight ───
  {
    id: 'w-bw-pushup',
    name: 'Push-Ups',
    sets: 4, reps: '12-15',
    notes: 'Keep core tight, full range of motion',
    videoQuery: 'perfect push up form tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-bw-diamond',
    name: 'Diamond Push-Ups',
    sets: 3, reps: '10-12',
    notes: 'Hands form a diamond shape, elbows close',
    videoQuery: 'diamond push up tutorial triceps',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-bw-dip',
    name: 'Tricep Dips',
    sets: 3, reps: '12-15',
    notes: 'Elbows close, lower until parallel',
    videoQuery: 'tricep dips chair form tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-bw-squat',
    name: 'Bodyweight Squat',
    sets: 4, reps: '15-20',
    notes: 'Chest up, knees track over toes',
    videoQuery: 'bodyweight squat form tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior', 'rogue'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-bw-pistol',
    name: 'Pistol Squat (Assisted)',
    sets: 3, reps: '5-8 each',
    notes: 'Hold a surface for balance if needed',
    videoQuery: 'pistol squat progression tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 3,
    category: 'strength',
  },
  {
    id: 'w-bw-pullup',
    name: 'Pull-Ups',
    sets: 3, reps: '6-10',
    notes: 'Full dead hang, chin over bar',
    videoQuery: 'pull up perfect form tutorial',
    equipment: ['bodyweight', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-bw-invrow',
    name: 'Inverted Row',
    sets: 3, reps: '10-12',
    notes: 'Body straight, pull chest to bar',
    videoQuery: 'inverted row tutorial bodyweight',
    equipment: ['bodyweight', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-bw-lunge',
    name: 'Walking Lunges',
    sets: 3, reps: '12 each leg',
    notes: 'Upright torso, knee close to floor',
    videoQuery: 'walking lunge perfect form',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior', 'rogue'],
    difficultyLevel: 1,
    category: 'strength',
  },
  // ─── WARRIOR: Dumbbells ───
  {
    id: 'w-db-bench',
    name: 'Dumbbell Bench Press',
    sets: 4, reps: '8-12',
    notes: 'Lower slowly, press explosively',
    videoQuery: 'dumbbell bench press form tutorial',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-db-row',
    name: 'Dumbbell Row',
    sets: 4, reps: '10-12 each',
    notes: 'Pull elbow to hip, squeeze at top',
    videoQuery: 'dumbbell row form tutorial back',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-db-shoulder',
    name: 'DB Shoulder Press',
    sets: 3, reps: '10-12',
    notes: 'Press overhead, arms parallel',
    videoQuery: 'dumbbell shoulder press tutorial',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-db-goblet',
    name: 'Goblet Squat',
    sets: 4, reps: '10-15',
    notes: 'Hold DB at chest, squat deep',
    videoQuery: 'goblet squat dumbbell tutorial',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-db-rdl',
    name: 'Romanian Deadlift',
    sets: 4, reps: '8-10',
    notes: 'Hip hinge, slight bend at knees',
    videoQuery: 'romanian deadlift dumbbell tutorial',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-db-curl',
    name: 'Bicep Curl',
    sets: 3, reps: '12-15',
    notes: 'Full contraction, no swinging',
    videoQuery: 'dumbbell bicep curl form tutorial',
    equipment: ['dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  // ─── WARRIOR: Full Gym ───
  {
    id: 'w-gym-bench',
    name: 'Barbell Bench Press',
    sets: 4, reps: '6-8',
    notes: 'Arch slightly, retract shoulder blades',
    videoQuery: 'barbell bench press form tutorial',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 3,
    category: 'strength',
  },
  {
    id: 'w-gym-squat',
    name: 'Barbell Back Squat',
    sets: 5, reps: '5',
    notes: 'Break parallel, brace core, drive up',
    videoQuery: 'barbell back squat form tutorial',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 3,
    category: 'strength',
  },
  {
    id: 'w-gym-deadlift',
    name: 'Deadlift',
    sets: 4, reps: '5',
    notes: 'Neutral spine, push floor away',
    videoQuery: 'barbell deadlift form beginner tutorial',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 3,
    category: 'strength',
  },
  {
    id: 'w-gym-ohp',
    name: 'Overhead Press',
    sets: 3, reps: '8-10',
    notes: 'Brace core, press straight overhead',
    videoQuery: 'overhead press barbell tutorial',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-gym-pulldown',
    name: 'Lat Pulldown',
    sets: 4, reps: '10-12',
    notes: 'Pull to upper chest, squeeze lats',
    videoQuery: 'lat pulldown tutorial form',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-gym-cable-row',
    name: 'Cable Row',
    sets: 3, reps: '12',
    notes: 'Keep torso upright, elbows back',
    videoQuery: 'cable row tutorial seated',
    equipment: ['full_gym'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  // ─── WARRIOR: Resistance Bands ───
  {
    id: 'w-rb-press',
    name: 'Band Push-Up',
    sets: 4, reps: '12-15',
    notes: 'Band across back adds resistance',
    videoQuery: 'resistance band push up tutorial',
    equipment: ['resistance_bands'],
    heroClasses: ['warrior'],
    difficultyLevel: 2,
    category: 'strength',
  },
  {
    id: 'w-rb-row',
    name: 'Band Seated Row',
    sets: 4, reps: '15',
    notes: 'Sit tall, pull band to abdomen',
    videoQuery: 'resistance band row seated tutorial',
    equipment: ['resistance_bands'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-rb-squat',
    name: 'Band Squat',
    sets: 4, reps: '15-20',
    notes: 'Band under feet, hold handles at shoulders',
    videoQuery: 'resistance band squat tutorial',
    equipment: ['resistance_bands'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  {
    id: 'w-rb-curl',
    name: 'Band Bicep Curl',
    sets: 3, reps: '15-20',
    notes: 'Stand on band, curl both arms',
    videoQuery: 'resistance band bicep curl tutorial',
    equipment: ['resistance_bands'],
    heroClasses: ['warrior'],
    difficultyLevel: 1,
    category: 'strength',
  },
  // ─── ROGUE: All Equipment ───
  {
    id: 'r-bw-burpee',
    name: 'Burpees',
    sets: 4, reps: '45 sec',
    notes: 'Max effort, jump and reach at top',
    videoQuery: 'burpee perfect form tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-bw-mountainclimber',
    name: 'Mountain Climbers',
    sets: 4, reps: '45 sec',
    notes: 'Drive knees to chest, keep hips low',
    videoQuery: 'mountain climbers tutorial core',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 1,
    category: 'hiit',
  },
  {
    id: 'r-bw-jumpsquat',
    name: 'Jump Squats',
    sets: 4, reps: '45 sec',
    notes: 'Land softly with bent knees',
    videoQuery: 'jump squat form tutorial plyometric',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-bw-highknees',
    name: 'High Knees',
    sets: 4, reps: '45 sec',
    notes: 'Drive arms, keep pace fast',
    videoQuery: 'high knees cardio tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 1,
    category: 'hiit',
  },
  {
    id: 'r-bw-tuckjump',
    name: 'Tuck Jumps',
    sets: 3, reps: '10',
    notes: 'Knees to chest at peak, land light',
    videoQuery: 'tuck jump plyometric tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 3,
    category: 'hiit',
  },
  {
    id: 'r-bw-lateralbounds',
    name: 'Lateral Bounds',
    sets: 4, reps: '10 each side',
    notes: 'Stick the landing, drive explosively',
    videoQuery: 'lateral bound plyometric tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-bw-sprint',
    name: 'Sprint Intervals',
    sets: 8, reps: '30s sprint / 30s rest',
    notes: 'Maximum effort on each sprint',
    videoQuery: 'sprint interval training tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-bw-boxjump',
    name: 'Box Jumps',
    sets: 4, reps: '10',
    notes: 'Step down controlled, dont jump down',
    videoQuery: 'box jump tutorial plyometric',
    equipment: ['bodyweight', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-gym-kb',
    name: 'Kettlebell Swings',
    sets: 5, reps: '15',
    notes: 'Hip drive, not a squat',
    videoQuery: 'kettlebell swing form tutorial',
    equipment: ['full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-gym-battle',
    name: 'Battle Ropes',
    sets: 4, reps: '30 sec',
    notes: 'Continuous wave motion, full power',
    videoQuery: 'battle ropes workout tutorial',
    equipment: ['full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  {
    id: 'r-db-thruster',
    name: 'Dumbbell Thruster',
    sets: 4, reps: '12',
    notes: 'Squat + shoulder press in one motion',
    videoQuery: 'dumbbell thruster tutorial',
    equipment: ['dumbbells', 'full_gym'],
    heroClasses: ['rogue'],
    difficultyLevel: 3,
    category: 'hiit',
  },
  {
    id: 'r-rb-squat-press',
    name: 'Band Squat & Press',
    sets: 4, reps: '15',
    notes: 'Explosive squat, press at top',
    videoQuery: 'resistance band squat press tutorial',
    equipment: ['resistance_bands'],
    heroClasses: ['rogue'],
    difficultyLevel: 2,
    category: 'hiit',
  },
  // ─── MONK: Mobility ───
  {
    id: 'm-bw-sunsalute',
    name: 'Sun Salutation Flow',
    sets: 3, reps: '5 rounds',
    notes: 'Breathe with every transition',
    videoQuery: 'sun salutation flow yoga tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-pigeon',
    name: 'Pigeon Pose',
    sets: 1, reps: '3 min each side',
    notes: 'Fold forward for deeper stretch',
    videoQuery: 'pigeon pose yoga tutorial hip opener',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-warrior3',
    name: 'Warrior III Balance',
    sets: 3, reps: '30 sec each',
    notes: 'Focus on a fixed point for balance',
    videoQuery: 'warrior 3 yoga pose tutorial balance',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 2,
    category: 'mobility',
  },
  {
    id: 'm-bw-plank',
    name: 'Plank Hold',
    sets: 4, reps: '45-60 sec',
    notes: 'Body straight as a board, breathe',
    videoQuery: 'perfect plank form tutorial core',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk', 'warrior'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-deadbug',
    name: 'Dead Bug',
    sets: 3, reps: '10 each side',
    notes: 'Lower back pressed to floor',
    videoQuery: 'dead bug exercise tutorial core',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-birddog',
    name: 'Bird Dog',
    sets: 3, reps: '12 each side',
    notes: 'Core engaged, move slow and controlled',
    videoQuery: 'bird dog exercise tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-supinetwist',
    name: 'Supine Spinal Twist',
    sets: 2, reps: '2 min each side',
    notes: 'Keep shoulder on floor, breathe into it',
    videoQuery: 'supine spinal twist yoga tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-hipflex',
    name: 'Hip Flexor Stretch',
    sets: 2, reps: '2 min each side',
    notes: 'Low lunge, squeeze glute of back leg',
    videoQuery: 'hip flexor stretch tutorial lunge',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-foamroll',
    name: 'Foam Rolling',
    sets: 1, reps: '5 min total',
    notes: 'Slow passes on tight areas, 30s each',
    videoQuery: 'foam rolling tutorial full body',
    equipment: ['bodyweight', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 1,
    category: 'mobility',
  },
  {
    id: 'm-bw-slrdl',
    name: 'Single-Leg Deadlift',
    sets: 3, reps: '10 each leg',
    notes: 'Hip hinge, keep hips square',
    videoQuery: 'single leg deadlift balance tutorial',
    equipment: ['bodyweight', 'dumbbells', 'full_gym'],
    heroClasses: ['monk'],
    difficultyLevel: 2,
    category: 'mobility',
  },
  // ─── MAGE: Cardio ───
  {
    id: 'mg-bw-zone2',
    name: 'Zone 2 Run',
    sets: 1, reps: '25-30 min',
    notes: 'Conversational pace, 65-75% max HR',
    videoQuery: 'zone 2 cardio running tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 2,
    category: 'cardio',
  },
  {
    id: 'mg-bw-warmup',
    name: 'Dynamic Warm-Up',
    sets: 1, reps: '5-8 min',
    notes: 'Leg swings, hip circles, arm swings',
    videoQuery: 'dynamic warm up running tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 1,
    category: 'cardio',
  },
  {
    id: 'mg-bw-tempo',
    name: 'Tempo Intervals',
    sets: 4, reps: '3 min hard / 2 min easy',
    notes: '80% effort on hard segments',
    videoQuery: 'tempo run interval training tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 3,
    category: 'cardio',
  },
  {
    id: 'mg-bw-fartlek',
    name: 'Fartlek Run',
    sets: 1, reps: '20 min',
    notes: 'Alternate easy and hard without stopping',
    videoQuery: 'fartlek training tutorial running',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 2,
    category: 'cardio',
  },
  {
    id: 'mg-bw-stair',
    name: 'Stair Climbs',
    sets: 6, reps: '1 min / 1 min rest',
    notes: 'Drive with arms, full step up',
    videoQuery: 'stair climbing workout tutorial',
    equipment: ['bodyweight', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 2,
    category: 'cardio',
  },
  {
    id: 'mg-bw-longrun',
    name: 'Long Slow Run',
    sets: 1, reps: '40-45 min',
    notes: 'Easy, sustainable pace — enjoy it',
    videoQuery: 'long slow distance running tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 2,
    category: 'cardio',
  },
  {
    id: 'mg-bw-cooldown',
    name: 'Post-Run Stretch',
    sets: 1, reps: '8-10 min',
    notes: 'Calves, quads, hamstrings, hip flexors',
    videoQuery: 'post run stretching routine tutorial',
    equipment: ['bodyweight', 'dumbbells', 'resistance_bands', 'full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 1,
    category: 'cardio',
  },
  {
    id: 'mg-gym-row',
    name: 'Rowing Machine',
    sets: 1, reps: '20 min',
    notes: 'Drive with legs first, then lean back',
    videoQuery: 'rowing machine form tutorial',
    equipment: ['full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 2,
    category: 'cardio',
  },
  {
    id: 'mg-gym-bike',
    name: 'Assault Bike',
    sets: 8, reps: '30s all-out / 90s easy',
    notes: 'Maximum effort on work intervals',
    videoQuery: 'assault bike interval workout tutorial',
    equipment: ['full_gym'],
    heroClasses: ['mage'],
    difficultyLevel: 3,
    category: 'cardio',
  },
];

// Helper to get exercises filtered by class and equipment
export function getExercisesFor(
  heroClass: HeroClassId,
  equipment: EquipmentType,
  difficultyLevel: 1 | 2 | 3
): ExerciseTemplate[] {
  return EXERCISE_LIBRARY.filter(
    (ex) =>
      ex.heroClasses.includes(heroClass) &&
      ex.equipment.includes(equipment) &&
      ex.difficultyLevel <= difficultyLevel
  );
}
