import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "flex-start",
    width: "100%",
    marginBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 10,
  },
  containerItems: {
    alignItems: "center",
    padding: 20,
  },
  sectionContainer: {
    height: "100%",
    flexDirection: "column",
    width: "100%",
  },
  sectionTitleContainer: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    marginBottom: 4,
  },
  sectionTitle: {
    color: "#ffffff",
    fontWeight: "600",
    marginLeft: 4,
    width: "100%",
  },
  option: {
    height: 50,
    flexDirection: "column",
    justifyContent: "center",
  },
  title: {
    color: "#ffffff",
    fontSize: 16,
  },
  deleteButton: {
    color: "red",
    fontSize: 16,
  },

  deletionButton: {
    display: "flex",
    alignItems: "center",
    borderRadius: 6,
    marginTop: 10,
    justifyContent: "center",
    height: 40,
    backgroundColor: "red",
    width: "30%",
  },

  inputContainer: {
    width: "90%",
    height: 60,
    backgroundColor: "#242424",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    paddingLeft: 10,
  },

  closeButton: {
    display: "flex",
    alignItems: "center",
    borderRadius: 6,
    marginTop: 10,
    justifyContent: "center",
    height: 40,
    backgroundColor: "#ffa726",
    width: "30%",
  },

  input: {
    width: "90%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.4,
    borderRadius: 10,
    height: 50,
    color: "white",
    fontWeight: "bold",
    borderColor: "orange",
  },
  userDeleteContainer: {
    position: "absolute",
    top: "35%",
    left: "15%",
    right: 0,
    bottom: 0,
    backgroundColor: "#242424",
    borderRadius: 10,
    width: "70%",
    height: "30%",
    gap: 10,
    zIndex: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  coverBlur: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    width: "100%",
    height: 1000,
    zIndex: 2,
  },
  subtitle: {
    color: "rgba(255, 255, 255, 0.6)",
  },
  hr: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    width: "100%",
    height: 1,
    position: "absolute",
    bottom: 0,
  },
  optionIcon: {
    position: "absolute",
    right: 0,
  },
});
